### ISSUE TITLE
CI job to validate README links

### ISSUE THREAD

**Issue by atc0005** [atc0005/notes#47]
Travis YAML config:

```yaml
language: ruby
rvm:
  - 2.5.3
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe --allow-redirect
notifications:
  email: false
```

Build Config:

```json
{
  "language": "ruby",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "rvm": [
    "2.5.3"
  ],
  "before_script": [
    "gem install awesome_bot"
  ],
  "script": [
    "awesome_bot README.md --allow-dupe --allow-redirect"
  ],
  "notifications": {
    "email": [
      {
        "enabled": false
      }
    ]
  }
}
```

refs https://travis-ci.org/github/dariubs/GoBooks/jobs/774279246/config
